### ISSUE TITLE
Feature: config validation for apisix in standalone mode

### ISSUE THREAD

**Issue by polaru** [api7/adc#103]
### Description

As a user running apisix in standalone mode, I would like to have a way to verify the configuration before submitting it to the instance.

In my case, we're running apisix in a kubernetes deployment, using configMaps for `config.yaml` and `apisix.yaml`. I would like to be able to verify the configuration in a step of the deployment pipeline, before updating the live/production configMaps.

**Comment by polaru** [comment]
Can this be linked to https://github.com/apache/apisix/pull/10630 ? I think it's relevant.

**Comment by juzhiyuan** [comment]
Thank you for mentioning this! But I think standalone doesn't work with adc, as adc uses ETCD as well. They're two different control ways. 🤔 Correct me if I'm wrong.

**Comment by polaru** [comment]
The other issue I linked (https://github.com/apache/apisix/pull/10630) doesn't mention `adc` and the suggested changes don't point to `adc` either; it looks to me like that person was trying to implement a test function in apisix directly, like `apisix test`. That's why I linked it. But if that's wrong, feel free to ignore the suggestion.

**Comment by juzhiyuan** [comment]
Yes. Standalone and ADC are two different data sources. 

ADC has supported to do validation for APISIX 3.6+. And if you're looking for validation against Standalone `apisix.yaml`, please refer to https://github.com/apache/apisix/pull/10630.
