### ISSUE TITLE
Bug: Validate of dicovery_type = eureka result in error

### ISSUE THREAD

**Issue by techgazer** [api7/adc#126]
### Current Behavior

When running adc validate with discovery_type: eureka, it always result in error: "failed to validate resource 'upstreams (eureka)': unexpected status code 400; value should match only one schema, but matches both schemas 1 and 2"

Following the apisix.yaml:
name: ""
upstreams:
- discovery_type: eureka
  nodes: []
  id: eureka
  name: "eureka"
  service_name: TEST
routes:
version: ""

### Exxpected Behavior

Expect to be successful. 

### Steps to Reproduce

1. Run adc validate
2. apisix.yaml
name: "test"
upstreams:
- discovery_type: eureka
  nodes: []
  id: eureka
  name: "eureka"
  service_name: TEST
routes:
version: "1.0.0"

### Environment

- APISIX version: 3.8.0
- ADC version (run `adc version`): 0.5.2
- Operating system (run `uname -a`): Linux 9935691b98c6 6.1.0-16-arm64 #1 SMP Debian 6.1.67-1 (2023-12-12) aarch64 Linux

**Comment by bzp2010** [comment]
The codebase has been significantly modified and it no longer uses Golang.
So I think the bug no longer exists.

I'm going to close this issue, and you can do a new test, if there are still errors, please open a new issue.
