### ISSUE TITLE
Feature: Reading from a constant file in adc

### ISSUE THREAD

**Issue by supreethmohan** [api7/adc#128]
### Description

Is there any way i can read from constant file in adc. For eg: I have a message "You cannot consume this service" repeated many times in my configuration file. I need a way to have this message in a variable and use the variable inside adc. Can you please suggest

**Comment by juzhiyuan** [comment]
@bzp2010 I think this can be done by YAML syntax? https://stackoverflow.com/questions/46641224/what-is-and-in-yaml-mean

**Comment by bzp2010** [comment]
Yes, using YAML anchors is fine. And, we're going to support reading values from environment variables in 0.12, and you can use it.

**Comment by juzhiyuan** [comment]
0.12 was released a few hours ago 🎉

**Comment by supreethmohan** [comment]
> @bzp2010 I think this can be done by YAML syntax? https://stackoverflow.com/questions/46641224/what-is-and-in-yaml-mean

Thanks a lot for this @juzhiyuan. I tried this out and it works!!!

**Comment by supreethmohan** [comment]
> Yes, using YAML anchors is fine. And, we're going to support reading values from environment variables in 0.12, and you can use it.

Thanks for this info @bzp2010. We will try the new version of adc
