### ISSUE TITLE
Bug: Erroneous judgment of values

### ISSUE THREAD

**Issue by bwangll** [api7/adc#129]
https://github.com/api7/adc/blob/567d5b89d0159bcd81588a2b08e8c9cb167839b8/pkg/api/apisix/types/resource_schema.go#L45
bug: Unable to set keepalived value
This should be the null case for assignments,and the default value should be 320

**Comment by bzp2010** [comment]
The codebase has been significantly modified and it no longer uses Golang.
So I think the bug no longer exists.

I'm going to close this issue, and you can do a new test, if there are still errors, please open a new issue.
