### ISSUE TITLE
Bug: upstream struct id, name, nodes allowed to be omitempty

### ISSUE THREAD

**Issue by bwangll** [api7/adc#130]
https://github.com/api7/adc/blob/567d5b89d0159bcd81588a2b08e8c9cb167839b8/pkg/api/apisix/types/types.go#L197
1. Setting upstream in the service allows you to leave id and name empty.
2. When the type is service discovery, nodes can be null.

**Comment by bzp2010** [comment]
The codebase has been significantly modified and it no longer uses Golang.
So I think the bug no longer exists.

I'm going to close this issue, and you can do a new test, if there are still errors, please open a new issue.
