### ISSUE TITLE
Bug: SSLS config key cannot be used with ADC v5.0 and v5.2

### ISSUE THREAD

**Issue by aalexiev42** [api7/adc#137]
### Current Behavior

SSL Struct contains both SNI and SNIs as required values. The two are mutually exclusive and this causes validation/ssls to fail with:
{"error_msg":"then clause did not match"}

### Exxpected Behavior

Expected behavior is for ADC "internal" validation to accept either sni or snis, but not both and allow for just one to be defined.

### Steps to Reproduce

With a config file, containing ssls definition run the following command. 
```
adc validate -f config.yaml
```
Issue: The internal Struct validation requires both sni and snis to be defined, but the apisix validation endpoint rejects the config when both are defined.

Example ssls definition in config.yaml:
```
ssls:
- cert: |-
    -----BEGIN CERTIFICATE-----
   ...
    -----END CERTIFICATE-----
  client:
    ca: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    depth: 10
  id: mtls-test
  key: |-
    -----BEGIN PRIVATE KEY-----
   ...
    -----END PRIVATE KEY-----
  snis:
  - mtls-test.test.x
  type: server
```

Possible solution: Take this with a grain of salt, because I'm not a GO developer or in depth with apisix.
change the following to make them omittable: pkg/api/apisix/types/types.go
```
-       SNI           string                 `json:"sni" yaml:"sni"`
-       SNIs          []string               `json:"snis" yaml:"snis"`
+       SNI           string                 `json:"sni,omitempty" yaml:"sni,omitempty"`
+       SNIs          []string               `json:"snis,omitempty" yaml:"snis,omitempty"`
```

### Environment

- APISIX version: 3.7.0
- ADC version (run `adc version`): v5.0 and v5.2 (tested)
- Operating system (run `uname -a`): Linux omitted-host 5.15.0-107-generic #117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bzp2010** [comment]
The codebase has been significantly modified and it no longer uses Golang.
So I think the bug no longer exists and now it will only use snis, which is mandatory.

I'm going to close this issue, and you can do a new test, and if there are still errors, please open a new issue.
