### ISSUE TITLE
Bug: re-use same upstream in different service 

### ISSUE THREAD

**Issue by pavankumar-siripurapu** [api7/adc#208]
### Current Behavior

In the older version of ADC, we could reuse upstream configurations at both the route and service levels (which could include multiple plugins). We would configure the upstream or the service for a route based on the required plugins. However, in the latest version of ADC, upstream reusability appears no longer available. This could potentially lead to the creation of duplicate upstream configurations across different services, causing the configuration file to grow unnecessarily. I have investigated all related issues but could not find any relevant solutions. Can you provide any guidance on how to avoid this duplication of upstream configurations? 

### Steps to Reproduce

adc diff -f config-v1.yaml

### Environment

- APISIX version: 3.9.1
- ADC version (run `adc version`): 0.16.0
- Operating system (run `uname -a`): linux

**Comment by pavankumar-siripurapu** [comment]
I think I got the solution for this. we can use YAML anchor syntax. If that's the approach please feel free to close the issue.

**Comment by ailoyu** [comment]
@pavankumar-siripurapu Hi there,

I want to ask that how can you reuse upstream by using YAML anchor syntax.

I already apply and got the error after applying:

adc sync -f config2.yaml --backend apisix --server <server_ip> --token <token>
Apache APISIX backend is experimental!
[10:49:07 PM] [ADC] › ▶  start     Load local configuration
[10:49:07 PM] [ADC] › ▶  start     Load /root/apisix-config/config2.yaml
[10:49:07 PM] [ADC] › ✔  success   Load /root/apisix-config/config2.yaml
[10:49:07 PM] [ADC] › ▶  start     Merge local configurations
[10:49:07 PM] [ADC] › ✔  success   Merge local configurations
[10:49:07 PM] [ADC] › ▶  start     Resolve value variables
[10:49:07 PM] [ADC] › ✔  success   Resolve value variables
[10:49:07 PM] [ADC] › ✔  success   Load local configuration
[10:49:07 PM] [ADC] › ▶  start     Lint configuration
[10:49:07 PM] [ADC] › ✖  error     Lint configuration
[10:49:07 PM] [ADC] › ✖  fatal     Error: Lint configuration
The following errors were found in configuration:
#1 raw error: {"code":"unrecognized_keys","keys":["upstreams"],"path":[],"message":"Unrecognized key(s) in object: 'upstreams'"}
NOTE: There are some unsummarizable errors in the lint results that are presented as "raw error". You can report such unexpected cases.

Here's Upstream Anchors, that is defined for reusable upstream configurations:

```

upstreams:
  # Default HTTP upstream template
  - &default-http-upstream
    name: default
    scheme: http
    type: roundrobin
    retry_timeout: 0
    pass_host: pass
    nodes:
      - host: httpbin.org
        port: 80
        weight: 1
        priority: 0

  # Default HTTPS upstream template
  - &default-https-upstream
    name: default
    scheme: https
    type: roundrobin
    retry_timeout: 0
    pass_host: pass
    nodes:
      - host: apps.learnwebservices.com
        port: 443
        weight: 1
        priority: 0

  # Custom timeout upstream template
  - &timeout-upstream
    type: roundrobin
    scheme: http
    pass_host: pass
    timeout:
      connect: 6
      send: 6
      read: 6
    keepalive_pool:
      idle_timeout: 60
      requests: 1000
      size: 320
    nodes:
      - host: 10.60.45.64
        port: 932
        weight: 1

  # Long timeout upstream template (for Kafka)
  - &long-timeout-upstream
    type: roundrobin
    pass_host: pass
    timeout:
      connect: 60
      send: 60
      read: 60
    keepalive_pool:
      idle_timeout: 60
      requests: 1000
      size: 320
    scheme: kafka
    name: kafka-loadtest
    nodes:
      - host: 10.60.45.50
        port: 9095
        weight: 1
      - host: 10.60.45.51
        port: 9095
        weight: 1
      - host: 10.60.45.52
        port: 9095
        weight: 1

  # SSE upstream template
  - &sse-upstream
    scheme: https
    type: roundrobin
    pass_host: node
    nodes:
      - host: www.esegece.com
        port: 2053
        weight: 1
        priority: 0


  # All methods template
  - &all-methods
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - HEAD
    - OPTIONS
    - CONNECT
    - TRACE
    - PURGE

services:
  - name: SOAP Service
    description: "This Service is for SOAP requests"
    upstream: *default-https-upstream
    routes:
      - uris:
          - /services/hello
        name: SOAP proxy
        methods:
          - POST
      - uris:
          - /SayHello
        name: REST to SOAP
        methods:
          - POST

  - name: httpbin Service
    description: "This is the httpbin Services proxy service"
    labels:
      app: httpbin
      custom_key: custom_value
    routes:
      - name: Generate UUID
        methods:
          - GET
        uris:
          - /uuid
      - name: Anything
        methods:
          - GET
        uris:
          - /anything
      - name: Rate Limited IP
        methods:
          - GET
        uris:
          - /ip
        plugins:
          limit-count:
            _meta:
              disable: false
            count: 2
            time_window: 10
            rejected_code: 429
            policy: local
    upstream: *default-http-upstream

  - name: SSE Service
    labels:
      service: sse
    upstream: *sse-upstream
    routes:
      - name: SSE API
        uris:
          - /sse
        methods:
          - GET

  - name: Test Service
    routes:
      - name: test
        uris:
          - /test
        methods: *all-methods
    upstream: *timeout-upstream


  - name: Kafka Service
    routes:
      - name: kafka-test
        uris:
          - /kafka
        methods: *all-methods
    upstream: *long-timeout-upstream

  - name: Catch All Service
    routes:
      - name: all
        uris:
          - /*
        methods: *all-methods


ssls: []

```
