### ISSUE TITLE
Bug: hosts field not handled correctly on APISIX service

### ISSUE THREAD

**Issue by cverdela** [api7/adc#215]
### Current Behavior

[dgc-test.yaml.zip](https://github.com/user-attachments/files/18158880/dgc-test.yaml.zip)
adc sync -f dgc-test.yaml
adc dump --with-id -o b.yaml

我导入了 dgc-test.yaml 文件，执行 adc sync 后，再用 adc dump --with-id -o b.yaml 导出文件，发现导出的 b.yaml 中没有了 hosts 字段。

### Exxpected Behavior

导出的 b.yaml 文件应该保留原有的 hosts 字段，保持与导入的 dgc-test.yaml 文件一致。

### Steps to Reproduce

adc sync -f dgc-test.yaml
adc dump --with-id -o b.yaml

### Environment

- APISIX version: 3.11.0
- ADC version (run `adc version`): 0.16.1
- Operating system (run `uname -a`):Linux hcy-esbd-06 5.10.0-198.0.0.111.oe2203sp3.x86_64 #1 SMP Wed May 8 16:22:48 CST 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bzp2010** [comment]
Released in [v0.17.0](https://github.com/api7/adc/releases/tag/v0.17.0)
