### ISSUE TITLE
Feature: adc dump 导出的 YAML 文件可以按照字典顺序或其他固定规则对条目进行排序，使得每次导出的文件格式一致，便于版本管理与差异比对。

### ISSUE THREAD

**Issue by cverdela** [api7/adc#216]
### Description

作为用户，我希望 adc dump 导出的 YAML 文件能够按条目进行排序，这样在使用 Git 进行版本管理时，可以更容易地看出哪些部分发生了变化。目前导出的文件通常会显示大量的 + 和 -，但实际上文件内容并没有实际差异，这使得版本差异显得很大，增加了比对的难度。

此功能有助于提高在 Git 中管理配置文件的清晰度，减少误解和多余的差异变动显示。

**Comment by bzp2010** [comment]
Released in [v0.17.0](https://github.com/api7/adc/releases/tag/v0.17.0)
