### ISSUE TITLE
CI: introduce  golangci-lint and gofmt

### ISSUE THREAD

**Issue by tao12345666333** [api7/adc#29]

**Comment by nottrif** [comment]
Hi @tao12345666333. I would like to work on this issue.
I would like some clarifications,
1) by golang-ci, did you mean golangci-lint?

**Comment by tao12345666333** [comment]
Yes! My typo.

Assigned, thanks

**Comment by nottrif** [comment]
@tao12345666333 I have already added a .yaml file that describes the lint workflow. I would like to test this locally before raising a PR, I found in golangci-lint documentation that [act](https://github.com/nektos/act#how-does-it-work) can be used locally to run Github Actions and test workflows locally. I wanted to know if this was a good way to test workflows?

**Comment by tao12345666333** [comment]
Yes. Or you can just raise a PR to run it
