### ISSUE TITLE
CI: publish container image in DockerHub registry.

### ISSUE THREAD

**Issue by tao12345666333** [api7/adc#32]

**Comment by OmAximani0** [comment]
Hi @tao12345666333 , I want to work on this.

**Comment by navendu-pottekkat** [comment]
@OmAximani0 Feel free to take this up.

@tao12345666333 Could you perhaps provide more details on what the Docker image name should be and add appropriate secrets needed to publish to Docker Hub?

**Comment by OmAximani0** [comment]
> @OmAximani0 Feel free to take this up.
> 
> @tao12345666333 Could you perhaps provide more details on what the Docker image name should be and add appropriate secrets needed to publish to Docker Hub?

Thank you @navendu-pottekkat

**Comment by tao12345666333** [comment]
@juzhiyuan Please help us add DockerHub username and password in secret.

@OmAximani0 you can add a new Dockerfile and add a job, when a new tag be created, this job will build and public a new image, named `api7/adc:<tag name >`


Thanks

**Comment by tao12345666333** [comment]
![2023-09-20 14-22-44屏幕截图](https://github.com/api7/adc/assets/3264292/46248c05-1a0f-487b-9555-a31e86967e7a)

@OmAximani0  You can use these variables in GitHub actions, which have already been configured by @juzhiyuan .

**Comment by OmAximani0** [comment]
Does `DOCKER_REGISTERY` includes user name and repository name ? If no can you give me some idea about what value  `DOCKER_REGISTERY` holds ?
