### ISSUE TITLE
UX: `adc configure` cannot be used for reconfiguring and does not allow access without token

### ISSUE THREAD

**Issue by navendu-pottekkat** [api7/adc#40]
**Current scenario**:

1. Running `adc configure` if you already have a `.adc.yaml` file will not let you reconfigure.
2. If token is not specified in the configuration, all commands fail because of missing token.

**Expected scenario**:

1. Running `adc configure` should let you reconfigure.

	It could also be that `.adc.yaml` could contain configurations for multiple APISIX instances and you can configure these multiple instances through the CLI. It could be something similar to contexts in Kubernetes where you can switch between multiple APISIX instances and select an active cluster to apply the CLI commands to.

2. Empty token should work and if APISIX server expects a token, the error message can be returned in the CLI indicating a missing token and asking the user to add a token.

**Comment by lingsamuel** [comment]
1. there is a `-f` option to overwrite existing config file now
2. client side doesn't know whether apisix needs a token or not. You are right, the token check should be removed

**Comment by navendu-pottekkat** [comment]
Maybe for a testing environment, they have disabled the API key. We don't recommend using APISIX without key but it is checked by APISIX. If there is a request without API key when APISIX expects a key, it should be the APISIX server that throws an error and not the client. So basically, the client should be naive. And we can only check for token in the server as it should be.

I think that is a better approach. WDYT?
