### ISSUE TITLE
Bug: config option is ignored with `diff`

### ISSUE THREAD

**Issue by davidlukac-wisi** [api7/adc#66]
### Current Behavior

Say I have different `.adc.yaml` files configured for different gateways.
```
$ cat dev/.adc.yaml
capath: ""
cert: ""
cert-key: ""
insecure: false
server: http://gateway.dev.mydomain.com:9180
token: somesecrettoken
```

I want to run `adc diff` commands specifying the config file. Command fails:
```
$ adc --config dev/.adc.yaml diff -f dev/config.yaml
Failed to read configuration file, please run `adc configure` first to configure ADC.
ADC isn't configured, run `adc configure` to configure ADC.

$ adc diff -f dev/config.yaml --config dev/.adc.yaml 
Failed to read configuration file, please run `adc configure` first to configure ADC.
ADC isn't configured, run `adc configure` to configure ADC.
```

### Exxpected Behavior

`--config path` flag should read the `adc` configuration from given file/path

### Steps to Reproduce

1. run `adc configure`
2. move `~/.adc.yaml` to project specific location
3. run `adc diff` with `--config` flag

### Environment

- APISIX version: 3.5.0
- ADC version (run `adc version`): v0.3.0/latest dev
- Operating system (run `uname -a`): Linux kubuntu 5.19.0-38-generic #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 17:33:16 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pottekkat** [comment]
@davidlukac-wisi Could you check if this issue persists on the latest main branch? I tried testing it locally and it seems to work as expected:


rm ~/.adc.yaml                                             
./bin/adc diff -f apisix.yaml --config ./adc.yaml
+++ service: "httpbin-service"
+++ route: "httpbin-route-anything"
+++ route: "httpbin-route-ip"
Summary: create 3, update 0, delete 0
