### ISSUE TITLE
Feature: Syncing Multiple Files/Folders with ADC for Configuration Efficiency

### ISSUE THREAD

**Issue by 223311** [api7/adc#97]
### Description

Hey team, 

I'm wondering if the ADC has the capability to sync multiple files or support syncing an entire folder. The reason behind this query is that, let's say, currently creating 20 routes and 20 consumers with Prometheus and other plugins enabled works well by adding configurations to a single file. However, if we scale this to over 100 routes, using a single file might not be the most efficient approach. Additionally, modifying values across thousands of lines can be quite challenging. Is there a method where we can create multiple files and have the ADC sync the entire folder?

**Comment by juzhiyuan** [comment]
This is achievable but not a high priority on my side 😅 

One direction is to work with APISIX's label attribute so we can split one monolith configuration into several chunks.

**Comment by 223311** [comment]
@juzhiyuan - could you please share some example on label attribute

**Comment by juzhiyuan** [comment]
Hi @223311, thank you for reaching out! Recently, I have discussed this with the team, and we will schedule a time to support this feature. I don't have a confirmed date, but it's on plan already. 

By the way, if you are interested in sharing your use cases (not only this one), we can have a call :) Kindly propose a few slots (I'm in SGT) or find a slot at https://api7.ai/contact.

**Comment by rstraszewski** [comment]
The feature would be a great help for maintaining large configuration in git repository.

**Comment by juzhiyuan** [comment]
Hi @223311 and @rstraszewski, this feature is supported in API7 Enterprise right now, we may support this as well for APISIX soon :)

**Comment by pavankumar-siripurapu** [comment]
Hi @juzhiyuan , Is there any update to support this feature in APISIX? I really appreciate any help you can provide.

**Comment by pottekkat** [comment]
ADC has been completely rewritten and now it supports this feature. Please take a look and let us know what's missing.

**Comment by juzhiyuan** [comment]
Hi @pavankumar-siripurapu, @bzp2010 has refactored the ADC implementation and once released, you can enjoy this feature :)

**Comment by bzp2010** [comment]
The New ADC has indeed been released and the feature has been implemented, so the issue is closed.
